name: weather_medallion
version: "1.0.0"
config-version: 2

profile: weather_medallion

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  weather_medallion:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
